version: '3.8'

services:
    app: #node.js app
        image: paulgl721/nodejs-portfolio:prodappVJVERSION
        build:
            context: .
            dockerfile: prodDockerfile
        volumes:
            - /glustervol/portfolio/paulgobero/configs/.env.prod:/nodeApp/configs/.env.prod
        ports:
            - "3000:3000"
        depends_on:
            - mongo
        networks: #networks to db and reverse proxy
            - dbapp-network
            - traefik_proxy-network 
        command: bash -c "npm run start"
        deploy: #using swarm to scale the service
            mode: replicated
            replicas: 2
            placement:
                constraints:
                    - node.role==manager
            labels: #generate configurations for the reverse proxy
                - "traefik.enable=true" # Enable the service
                - "traefik.http.routers.app.rule=Host(`www.paulgobero.com`)"
                - "traefik.http.services.app-service.loadbalancer.server.port=3000"
                - "traefik.http.routers.app.entrypoints=web,websecure"
                - "traefik.http.routers.app.tls=true" #enable tls
                - "traefik.http.routers.app.tls.certresolver=production" #certificate
            restart_policy: #how to restart containers when they exit
                condition: any
                delay: 20s
                max_attempts: 10
                window: 120s
            update_config: #how the service should be updated
                parallelism: 2
                delay: 10s
                failure_action: rollback
                order: start-first
            rollback_config: #how the service should be rolled back in case an update fails
                parallelism: 2
                delay: 10s  

#create the communication networks between the containers
networks:
    traefik_proxy-network:
        external: true

