version: '3.8'

services:
    app: #node.js app
        image: paulgl721/nodejs-portfolio:prodappVJVERSION
        build:
            context: .
            dockerfile: prodDockerfile
        volumes:
            - /glustervol/portfolio/paulgobero/configs/.env.prod:/nodeApp/configs/.env.prod
        networks: #networks to db and reverse proxy
            - traefik_proxy-network 
        command: bash -c "./wait-for hamongodb_mongo1:27017 --timeout=600 --npm run start" #wait for mongodb
        deploy: #using swarm to scale the service to three nodes
            mode: replicated
            replicas: 3
            placement:
                preferences:
                  - spread: node.hostname
            labels: #generate configurations for the reverse proxy
                - "traefik.enable=true" # Enable the service
                - "traefik.http.routers.app.rule=Host(`www.paulgobero.com`)"
                - "traefik.http.services.app-service.loadbalancer.server.port=3000"
                - "traefik.http.routers.app.entrypoints=web,websecure"
                - "traefik.http.routers.app.tls=true" #enable tls
                - "traefik.http.routers.app.tls.certresolver=production" #certificate
            restart_policy: #how to restart containers when they exit
                condition: any
                delay: 20s
                max_attempts: 10
                window: 120s
            update_config: #how the service should be updated
                parallelism: 1
                delay: 10s
                failure_action: rollback
                order: start-first
            rollback_config: #how the service should be rolled back in case an update fails
                parallelism: 1
                delay: 10s  

#create the communication networks between the containers
networks:
    traefik_proxy-network:
        external: true
