
//define variables
def staged_files
def testResult
def no_of_prs

pipeline {
	//run on different agents
	agent none

	//define env variables
	environment {
		VERSION="0.1.${BUILD_NUMBER}"
		BASE_DIRECTORY='paulgobero_com'
		REMOTE_USER='deployuser1'
		REMOTE_DIR='PORTFOLIO'
		REMOTE_FOLDER='paulgobero_com'
		STACKNAME='portfolio'
		GIT_REPO='git@github.com:Paul-GL721/portfolio.git'
		GH_TOKENCRED=credentials('jenkins-post-pr-portfolio')
		EMAIL_TO='team@paulgobero.com'
	}

	stages {
		stage('Merge development and staging branches') {
			//Execute if its the develpment branch
			when {
				branch 'development'
			}
			//where to execute
			agent {
				label 'buildnode'
			}
			steps {
				echo '..................Merging if anyfiles have changed................'
				
				//with github credentials stored in jenkins
				sshagent (credentials: ['e833b0c8-199a-4d54-a272-a021d20c622b']) {
					script {
						//make the build script executable
						sh 'chmod +x ./${BASE_DIRECTORY}/jenkins-scripts/merge-code-step.sh'

						//build the image
						sh '''./${BASE_DIRECTORY}/jenkins-scripts/merge-code-step.sh '''

						//Uncomment if they are changes made and commited to the staging branch directly
						/*sh('git stash')
						sh('git pull')
						sh('git push ${GIT_REPO}')*/

						//Find the number of staged files
						staged_files = sh(script: 'git diff --cached --numstat | wc -l', returnStdout: true) as Integer

						//if they are (staged_files) more than zero, commit the files and push to remote repo
						if(staged_files > 0) {
							echo "They are ${staged_files} staged files"
							sh('git commit -m "Merged from development branch: Build version ${VERSION} " ')
							sh('git push ${GIT_REPO}')
						}
						else {
							echo "There no commits to make"
						}
					}
				}
			}
		}

		stage('Testing') {
			//Execute if its the staging branch
			when {
				branch 'staging'
			}
			//execute the code on the testing machine
			agent {
				label 'testnode'
			}
			steps {
				echo '..................Runing Tests................'
				//test code
				echo "Testing the code in the git repository"
			}
		}

		stage('Build and taged image') {
			//Execute if its the staging branch
			when {
				branch 'staging'
			}
			//build the docker image and push to dockerhub
			agent {
				//build on build agent
				label 'buildnode'
			}
			steps {
				echo '..............Building and Publishing Docker Images................'
				echo 'Creating a taged image'

				//make the build script executable
				sh 'chmod +x ./${BASE_DIRECTORY}/jenkins-scripts/build-step.sh'

				//build the image
				sh '''./${BASE_DIRECTORY}/jenkins-scripts/build-step.sh '''+VERSION+''' '''
			}
		}

		stage('Deploy on an EC2 instance') {
			//Execute if its the staging branch
			when {
				branch 'staging'
			}
			//Using ansible to deploy on an EC2 instance
			agent {
				label 'deploynode'
			}
			steps {
				echo '..................Deploying with ansible................'
				script{
					//run ansible-playbook
					sh "ansible-playbook ./${BASE_DIRECTORY}/ansible/portfolio-playbook.yml -i ./${BASE_DIRECTORY}/ansible/inventory.ini --extra-vars=\"{'REMOTE_USER': '${env.REMOTE_USER}', 'GIT_REPO': '${env.GIT_REPO}', 'REMOTE_DIR': '${env.REMOTE_DIR}', 'REMOTE_FOLDER': '${env.REMOTE_FOLDER}', 'STACKNAME': '${env.STACKNAME}', 'VERSION': '${env.VERSION}'}\" -vvv"
				}
			}
		}

		stage('Create pull request') {
			//Execute if its the staging branch
			when {
				branch 'staging'
			}
			//Use a docker image with gitcli installed
			agent {
				label 'buildnode'
			}
			steps {
				script {
					echo '.............Creating pull request on production branch..........'
					sh 'gh --version'					
					sh 'echo \$GH_TOKENCRED_PSW|gh auth login --hostname github.com --with-token'
					sh 'gh auth status'
					
					//How many prs exist in github repo
					no_of_prs = sh(script: "gh pr view staging --json number,state ") 
					echo "Check, number of prs on Githuh: They are ${no_of_prs}"

					//if the prs are less than 1, Raise a new pull request on the production branch, 
					//else a new commit will be automatically tracked by the existing pr
					if(no_of_prs == null) {
						echo "They are ${no_of_prs} pull requests from staging to production"
						echo '.............Creating pull request on production branch..........'
						sh 'gh pr create --title "Staging branch v$VERSION was successful" --body "Staging branch version$VERSION was successfully tested and deployed needs to be merged into production" --base production --head staging'
					}
					else {
						echo "They are/is ${no_of_prs} pull request(s) from staging to production, commit will be automatically tracked"
					}
					sh 'gh auth logout --hostname github.com'
				}				
			}
		}
	}

	post {
		success {
			echo '...........JOB EXECUTED SUCCESSFULLY...........'
			emailext body: 'Your code successfully executed. Check console output at $BUILD_URL to view the results. ',
			subject: 'Stable staging build in Jenkins: $PROJECT_NAME - #$BUILD_NUMBER', 
            to: "${EMAIL_TO}" 
		}

		failure {
			echo '...........JOB WAS UNSUCCESSFULL................'
			emailext body: 'The commit you made failed. Check console output at $BUILD_URL to view the results. \n\n ${CHANGES} \n\n -------------------------------------------------- \n${BUILD_LOG, maxLines=100, escapeHtml=false}',
			subject: 'Unstable build in Jenkins: $PROJECT_NAME - #$BUILD_NUMBER', 
            to: "${EMAIL_TO}" 
		}
	} 
}