pipeline {
	//run on different agents
	agent none

	//define env variables
	environment {
		VERSION="0.0.${BUILD_NUMBER}"
		BASE_DIRECTORY='paulgobero_com'
		//DOCKERHUB_CREDENTIALS=credentials('jenkins-to-dockerhub')
	}

	stages {
		stage('Testing') {
			//execute the code on the testing machine
			agent {
				label 'testnode'
			}
			steps {
				//test code
				echo "Testing the code in the git repository"
			}
		}

		stage('Build and taged image') {
			//build the docker image and push to dockerhub
			agent {
				//build on build agent
				label 'buildnode'
			}
			steps {
				echo 'Creating a taged image'

				//make the build script executable
					sh 'chmod +x ./${BASE_DIRECTORY}/jenkins-scripts/build-step.sh'

				//build the image
					sh '''./${BASE_DIRECTORY}/jenkins-scripts/build-step.sh '''+VERSION+''' '''
			}
		}

		stage('Deploy on an EC2 instance') {
			//Using ansible to deploy on an EC2 instance
			agent {
				label 'deploynode'
			}
			steps {
				echo 'Deploy with ansible'
			}
		}
	}
}