version: '3.8'

services:
    app:
        image: paulgl721/nodejs-portfolio:stagingVJVERSION
        build: #build from stagedockerfile
            context: .
            dockerfile: stagedockerfile
        #volumes:       
            #- /mnt/portfolio/paulgobero/configs/.env.stage:/nodeApp/stageconfigs/.env.stage
        ports:
            - "3001:3001"
        depends_on:
            - stagemongo
        networks: #networks to db and reverse proxy
            - stagedbapp-network
            - traefik_proxy-network 
        deploy: #using swarm to scale the service
            mode: replicated
            replicas: 2
            placement:
                constraints:
                    - node.role==manager
            labels: #generate configurations for the reverse proxy
                - "traefik.enable=true" # Enable the service
                - "traefik.http.routers.app.rule=Host(`stagingwww.paulgobero.com`)"
                - "traefik.http.services.app-service.loadbalancer.server.port=3001"
                - "traefik.http.routers.app.entrypoints=web,websecure"
                - "traefik.http.routers.app.tls=true" #enable tls
                - "traefik.http.routers.app.tls.certresolver=production" #certificate
            restart_policy: #how to restart containers when they exit
                condition: any
                delay: 7s
                max_attempts: 10
                window: 120s
            update_config: #how the service should be updated
                parallelism: 2
                delay: 10s
                failure_action: rollback
                order: start-first
            rollback_config: #how the service should be rolled back in case an update fails
                parallelism: 2
                delay: 10s  

    #mongodb database service
    stagemongo:
        image: mongo:6
        env_file:
            - /mnt/portfolio/paulgobero/configs/.env.stage
        ports:
            - "27020:27020"
        volumes:
            - /mnt/portfolio/paulgobero/database/stagedatabase:/data/db
        networks: #networks to application and admin
            - stagedbapp-network
            - stagedbadmin-network
        deploy: #deploy the db on the manager node
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.role==manager
            restart_policy: #how to restart containers when they exit
                condition: any
                delay: 7s
                max_attempts: 10
                window: 120s

    #web-based mongoDB admin interface
    mongodbadmin:
        image: mongo-express:latest
        ports:
            - "8082:8082"
        env_file:
            - /mnt/portfolio/paulgobero/configs/.env.stage
        depends_on:
            - stagemongo
        networks: 
            - traefik_proxy-network #links to traefik proxy
            - stagedbadmin-network #link to database
        deploy: #deploy on the manager node
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.role==manager
            labels: #generate configurations for the reverse proxy
                - "traefik.enable=true" # Enable the service
                - "traefik.http.routers.mongodbadmin.rule=Host(`stagingmongodbadmin.paulgobero.com`)"
                - "traefik.http.services.mongodbadmin-service.loadbalancer.server.port=8082"
                - "traefik.http.routers.mongodbadmin.entrypoints=web,websecure"
                - "traefik.http.routers.mongodbadmin.tls=true" #enable tls
                - "traefik.http.routers.mongodbadmin.tls.certresolver=production" #certificate
            restart_policy: #how to restart containers when they exit
                condition: any
                delay: 7s
                max_attempts: 10
                window: 120s

#create the communication networks between the containers
networks:
    stagedbapp-network: #link db and webapp
        driver: overlay
        attachable: true
    stagedbadmin-network:
        driver: overlay
        attachable: true
    traefik_proxy-network:
        external: true

