version: '3.8'

services:
    app:
        image: paulgl721/testnodejs-portfolio
        volumes:
                # - ".:/nodeApp"    
            - /mnt/portfolio/paulgobero/stageconfigs/.env.stage:/nodeApp/stageconfigs/.env.stage
        build:
            context: .
            dockerfile: testdockerfile
        ports:
            - "3001:3001"
        depends_on:
            - mongo 

    #mongodb database service
    mongo:
        image: paulgl721/testmongo-portfolio
        build:
            context: ./mongodb
            dockerfile: Dockerfile
        env_file:
            - /mnt/portfolio/paulgobero/stageconfigs/.env.stage
        ports:
            - "27017:27017"
        volumes:
            - /mnt/portfolio/paulgobero/stagedatabase:/data/db
    
    #web-based mongoDB admin interface
    mongodbadmin:
        image: mongo-express:latest
        ports:
            - "8081:8081"
        env_file:
            - /mnt/portfolio/paulgobero/stageconfigs/.env.stage
        depends_on:
            - mongo
      
