version: '3.8'

services:
    testapp:
        image: paulgl721/testnodejs-portfolio
        env_file:
            - ./configs/.env.test
        build:
            context: .
            dockerfile: testdockerfile
        ports:
            - "3002:3002"
        depends_on:
            - testmongodb 
        command: bash -c "sleep 20 && ./wait-for testmongodb:27018 --timeout=600 -- npm run test"
        networks:
            - testnetwork

    #mongodb database service
    testmongodb:
        image: paulgl721/testmongo-portfolio
        build:
            context: ./mongodb
            dockerfile: Dockerfile
        env_file:
            - ./configs/.env.test
        ports:
            - "27018:27017"
        restart: always
        volumes:
            - testdatabase:/data/db     
        networks:
            - testnetwork
    
    #web-based mongoDB admin interface
    testmongodbadmin:
        image: mongo-express:latest
        restart: always
        ports:
            - "8082:8081"
        env_file:
            - ./configs/.env.test
        depends_on:
            - testmongodb
        networks:
            - testnetwork

volumes:
    testdatabase:
networks:
    testnetwork:

      
