version: '3.8'

services:
    app:
        image: paulgl721/nodejs-portfolio
        volumes:
            - ".:/nodeApp"     
        build:
            context: .
            dockerfile: testdockerfile
        ports:
            - "3001:3001"
        depends_on:
            - mongo 

    #mongodb database service
    mongo:
        image: paulgl721/mongo-portfolio
        build:
            context: ./mongodb
            dockerfile: Dockerfile
        env_file:
            - /mnt/portfolio/paulgobero/configs/.env.stage
        ports:
            - "27018:27018"
        volumes:
            - /mnt/portfolio/paulgobero/stagedatabase:/data/db
    
    #web-based mongoDB admin interface
    mongodbadmin:
        image: mongo-express:latest
        ports:
            - "8082:8082"
        env_file:
            - /mnt/portfolio/paulgobero/configs/.env.stage
        depends_on:
            - mongo
      
