---
#test ansible connection
- name: Run the test playbook 
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Get the username running this playbook
      become: false
      local_action: command whoami
      register: username_on_the_host
    - name: Display the User name
      ansible.builtin.debug:
        msg: "Hello User {{ username_on_the_host.stdout }} from Jenkins and Ansible!!"

#deploy to swarm node
- name: Deploy to docker swarm
  hosts: staging
  tasks:
    - name: check availabilty of server
      become: true
      remote_user: "{{ REMOTE_USER }}"
      action: ping

    - name: Create a directory
      ansible.builtin.file:
        path: /home/{{ REMOTE_USER }}/{{ REMOTE_DIR }}
        state: directory
        mode: u=rwx,g=rwx,o=rx
        recurse: yes
        owner: "{{ REMOTE_USER }}"
        group: "{{ REMOTE_USER }}"

    - name: Clone the master branch of the repository
      ansible.builtin.git:
        repo: "{{ GIT_REPO }}"
        dest: /home/{{ REMOTE_USER }}/{{ REMOTE_DIR }}
        single_branch: yes
        version: master
        force: yes
        key_file: /home/{{ REMOTE_USER }}/.ssh/ansiblegithub

    - name: Replace JVERSION Placeholders in docker-compose.yml 
      shell: |
        sed -i -e 's/JVERSION/{{ VERSION }}/g' /home/{{ REMOTE_USER }}/{{ REMOTE_DIR }}/{{ REMOTE_FOLDER }}/docker-compose.yml

    - name: change directory, and deploy stack
      ansible.builtin.shell:
      args:
        chdir: /home/{{ REMOTE_USER }}/{{ REMOTE_DIR }}/{{ REMOTE_FOLDER }}
        cmd: docker stack deploy -c docker-compose.yml {{ STACKNAME }}
